name: fuel-service

services:
  api:
    build:
      context: src/
      dockerfile: Dockerfile
      network: host
    image: fuel-service/api:latest
    ports:
      - "8080:8080"
    restart: "unless-stopped"
    env_file:
      - env/secrets.env
      - env/config.env
    networks:
      - api-network
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: "unless-stopped"
    env_file:
      - env/secrets.env
      - env/config.env
    ports:
      - "5433:5432"
    networks:
      - api-network
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw

networks:
  api-network:
    driver: bridge
